Repository armosec/kubecop, pull requests merged in 2023-12, with the labels that each got.

#70 Preventing from using incomplete application profiles
  pkg/approfilecache/cache.go
Labels: requires-system-test, bug_fix

#69 Adding title to alert manager messages
  pkg/engine/rule/r0005_unexpected_domain_request.go
  pkg/exporters/alert_manager.go
Labels: enhancement, refactoring

#72 Fixing rules priorities
  pkg/engine/rule/r0001_unexpected_process_launched.go
  pkg/engine/rule/r0002_unexpected_file_access.go
  pkg/engine/rule/r0003_unexpected_system_call.go
  pkg/engine/rule/r0004_unexpected_capability_used.go
  pkg/engine/rule/r0005_unexpected_domain_request.go
  pkg/engine/rule/r1000_exec_from_malicious_source.go
  pkg/engine/rule/r1001_exec_binary_not_in_base_image.go
  pkg/engine/rule/r1002_load_kernel_module.go
  pkg/engine/rule/r1003_malicious_ssh_connection.go
  pkg/engine/rule/r1004_exec_from_mount.go
  pkg/engine/rule/r1005_kubernetes_client_executed.go
  pkg/engine/rule/rule.go
  pkg/exporters/utils.go
  pkg/exporters/utils_test.go
Labels: refactoring

#73 Feature/unshare rule
  chart/kubecop/crds/runtime-rule-binding.crd.yaml
  cmd/rule_md_gen/generate_md.go
  pkg/engine/rule/README.md
  pkg/engine/rule/factory.go
  pkg/engine/rule/r1006_unshare_system_call.go
  pkg/engine/rule/r1006_unshare_system_call_test.go
  pkg/rulebindingstore/README.md
  pkg/rulebindingstore/crd.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-all-pods.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx-default-ns.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-default-ns.yaml
  scripts/setup-system-test-cluster.sh
  scripts/validate-crd.sh
Labels: enhancement, refactoring

#76 Feature/r1007 crypto miner
  chart/kubecop/crds/runtime-rule-binding.crd.yaml
  pkg/engine/rule/README.md
  pkg/engine/rule/factory.go
  pkg/engine/rule/r1007_crypto_miners.go
  pkg/engine/rule/r1007_crypto_miners_test.go
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-all-pods.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx-default-ns.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-default-ns.yaml
Labels: enhancement

#83 Improving stability of application profile generation
  .gitignore
  cmd/main.go
  go.mod
  go.sum
  pkg/engine/container.go
Labels: requires-system-test

#84 Bumping ig version to 0.23.0 in order to support aws arm nodes
  go.mod
  go.sum
Labels: enhancement, requires-system-test

#88 Case Insensitive Comparison of Profile Kinds and Kapprofiler Upgrade
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/exporters/alert_manager.go
  resources/system-tests/kubecop-values.yaml
Labels: enhancement, requires-system-test, bug_fix

#97 Fixing logs
  pkg/exporters/stdout_exporter.go
Labels: Bug fix

#93 Deliberately malicious container and its tests
  chart/kubecop/templates/default-rule-binding.yaml
  cmd/malicious-exe/Containerfile
  cmd/malicious-exe/malicious.go
  etc/app-profile.crd.yaml
  go.mod
  go.sum
  pkg/engine/rule/r1007_crypto_miners.go
  system-tests/all_alerts_from_malicious_app.py
  system-tests/basic_alert_tests.py
  system-tests/basic_load_activities.py
  system-tests/crashlooping-container/crashlooping-deploy.yaml
  system-tests/creation_app_profile_memory_leak.py
  system-tests/kill_in_the_middle.py
  system-tests/kubernetes_wrappers.py
  system-tests/load_10k_alerts_no_memory.py
  system-tests/promtopic.py
  system-tests/resources/locust-deployment.yaml
  system-tests/resources/malicious-job-app-profile.yaml
  system-tests/resources/malicious-job.yaml
  system-tests/resources/nginx-app-profile.yaml
  system-tests/resources/nginx-deployment.yaml
  system-tests/resources/nginx-service.yaml
  system-tests/rule_binding_apply_test.py
  system-tests/run.py
Labels: requires-system-test

#99 Bumping kapprofiler to v0.0.32 which fixes bad crd's patching
  go.mod
  go.sum
Labels: enhancement, requires-system-test

#100 Feature/prometheus exporter
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/approfilecache/stats_prometheus.go
  pkg/engine/engine.go
  pkg/engine/processing.go
  pkg/engine/router.go
  pkg/engine/stats_prometheus.go
Labels: enhancement

#101 Splitting node-agent and controller
  chart/kubecop/templates/controller-statefulset.yaml
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  cmd/main.go
  go.mod
  go.sum
Labels: enhancement, requires-system-test

#102 Updating system to use labels instead of annotations
  dev/nginx/nginx-app-profile.yaml
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  system-tests/finalization_alert_test.py
  system-tests/resources/malicious-job-app-profile.yaml
  system-tests/resources/nginx-app-profile.yaml
  system-tests/run.py
Labels: enhancement, requires-system-test, Tests

#103 Replacing the object informer implementation in cache
  Makefile
  go.mod
  go.sum
  pkg/approfilecache/cache.go
Labels: enhancement

#98 Adding params to readme
  pkg/engine/rule/README.md
Labels: documentation

#92 Feature/syslog exporter
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  go.mod
  go.sum
  pkg/engine/rule/r1001_exec_binary_not_in_base_image.go
  pkg/exporters/README.md
  pkg/exporters/exporters_bus.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
Labels: enhancement

#105 Improving memory usage by omitting pre-listing of application profiles
  go.mod
  go.sum
  pkg/approfilecache/cache.go
Labels: bug_fix

#106 Adding fixed version of kapprofiler
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/templates/default-rule-binding.yaml
  chart/kubecop/values.yaml
  go.mod
  go.sum
  pkg/engine/container.go
  pkg/engine/poll.go
Labels: enhancement, requires-system-test

#110 Readme/extending on getting started
  .github/workflows/ci.yaml
  .github/workflows/system-tests.yaml
  README.md
  docs/development.md
Labels: documentation

#112 Fixing message id and test
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
Labels: enhancement, bug_fix

#96 Adding demo files
  demo/general_attack/commands.md
  demo/general_attack/webapp/Containerfile
  demo/general_attack/webapp/index.html
  demo/general_attack/webapp/ping-app.yaml
  demo/general_attack/webapp/ping.php
  demo/general_attack/webapp/setup.sh
  demo/miner/Dockerfile
  demo/miner/miner-pod.yaml
  demo/miner/xmr-k8s-miner.py
Labels: enhancement, Possible security concern

#109 Removing unshare syscall usage from default rule bindings
  chart/kubecop/templates/default-rule-binding.yaml
  system-tests/all_alerts_from_malicious_app.py
Labels: enhancement, requires-system-test

#114 Feature/csv exporter
  README.md
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  pkg/exporters/README.md
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/exporters_bus.go
Labels: enhancement

#115 Create SECURITY.md
  SECURITY.md
Labels: documentation

#108 Feature/finalize jitter
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  cmd/main.go
  go.mod
  go.sum
  resources/system-tests/kubecop-values.yaml
  system-tests/creation_app_profile_memory_leak.py
  system-tests/finalization_alert_test.py
  system-tests/load_10k_alerts_no_memory.py
Labels: enhancement, requires-system-test

#116 Changing Application Profile reference from pointer to object
  cmd/main.go
  pkg/approfilecache/cache.go
  pkg/approfilecache/cache_test.go
Labels: requires-system-test, Bug fix

#117 Adding fields
  pkg/exporters/csv_exporter.go
Labels: bug_fix

#119 Implementing eBPF error metrics for Prometheus
  go.mod
  go.sum
  pkg/engine/router.go
  pkg/engine/stats_prometheus.go
Labels: enhancement

#118 Feature/crypto miner improve
  chart/kubecop/crds/runtime-rule-binding.crd.yaml
  chart/kubecop/templates/default-rule-binding.yaml
  pkg/engine/rule/README.md
  pkg/engine/rule/r1007_crypto_miners.go
  pkg/engine/rule/r1007_crypto_miners_test.go
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-all-pods.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx-default-ns.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-app-nginx.yaml
  pkg/rulebindingstore/testdata/rulebindingsfiles/all-rules-for-default-ns.yaml
  scripts/resolve-pools-addresses.sh
  system-tests/all_alerts_from_malicious_app.py
Labels: enhancement, requires-system-test
