Repository armosec/kubecop, pull requests merged in 2024-01, with the labels that each got.

#121 Adding dockerfile and malware database filter
  resources/clamav/Dockerfile
  resources/clamav/create-filtered-clam-db.sh
  resources/clamav/init.sh
Labels: enhancement

#120 Feature/clamav
  chart/kubecop/files/clamd.conf
  chart/kubecop/files/freshclam.conf
  chart/kubecop/templates/configmap.yaml
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  cmd/main.go
  demo/fileless_exec/kubernetes-manifests.yaml
  dev/devpod-clamav.yaml
  go.mod
  go.sum
  pkg/engine/processing.go
  pkg/exporters/README.md
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/exporter.go
  pkg/exporters/exporters_bus.go
  pkg/exporters/stdout_exporter.go
  pkg/exporters/stdout_exporter_test.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
  pkg/scan/clamav/clamav.go
  pkg/scan/clamav/config.go
  pkg/scan/types.go
  resources/clamav/Dockerfile
  resources/clamav/create-filtered-clam-db.sh
  resources/clamav/init.sh
  scripts/setup-system-test-cluster.sh
Labels: requires-system-test

#129 Update/demo readme
  demo/README.md
  demo/assets/alertmanager.png
  demo/assets/fileless-malware.png
  demo/assets/kubectl.png
  demo/assets/ls.png
  demo/assets/ping.png
  demo/assets/pods.png
  demo/assets/service-account-token.png
  demo/assets/webapp.png
  demo/fileless_exec/kubernetes-manifest.yaml
Labels: enhancement

#130 Update README.md
  demo/README.md
Labels: documentation

#133 Bugfix/clamav
  chart/kubecop/files/clamd.conf
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  cmd/main.go
  dev/devpod-clamav.yaml
  pkg/scan/clamav/clamav.go
  pkg/scan/clamav/config.go
  resources/clamav/Dockerfile
Labels: enhancement, Bug fix

#132 Adding ClamAV demo
  README.md
  demo/README.md
  demo/assets/malwares.png
  demo/general_attack/webapp/ping-app.yaml
  demo/malwares_image/Containerfile
  dev/devpod-clamav.yaml
Labels: documentation, enhancement

#128 Feature/multiple am
  README.md
  chart/demo/.helmignore
  chart/demo/Chart.yaml
  chart/demo/templates/_helpers.tpl
  chart/demo/templates/alertmanager-configmap.yaml
  chart/demo/templates/alertmanager-service.yaml
  chart/demo/templates/alertmanager.yaml
  chart/demo/values.yaml
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  pkg/exporters/README.md
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/exporters_bus.go
  resources/latest/kubecop-values.yaml
  resources/system-tests/kubecop-values.yaml
Labels: enhancement, requires-system-test

#135 Fixing missing netcat in image
  resources/clamav/Dockerfile
Labels: Bug fix

#137 Improving unit tests of the engine
  cmd/main.go
  pkg/engine/container.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/processing.go
  pkg/engine/rule/r1001_exec_binary_not_in_base_image.go
  pkg/exporters/exporters_bus.go
  pkg/scan/clamav/clamav.go
  pkg/scan/clamav/config.go
Labels: enhancement, Tests

#136 Adding Gomemlimit to fix slow memory leak
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
Labels: enhancement

#138 Skipping failed application profiles
  chart/kubecop/values.yaml
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/engine/engine_test.go
Labels: enhancement, requires-system-test

#139 Feature/clamav enrich
  cmd/main.go
  cmd/single-tracer-test/single-trace.go
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/engine/container.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/engine/poll.go
  pkg/engine/processing.go
  pkg/engine/router.go
  pkg/engine/rule/r0002_unexpected_file_access.go
  pkg/engine/rule/r0006_unexpected_service_account_token_access.go
  pkg/engine/rule/r0007_kubernetes_client_executed.go
  pkg/engine/rule/r1001_exec_binary_not_in_base_image.go
  pkg/engine/rule/r1003_malicious_ssh_connection.go
  pkg/engine/rule/r1004_exec_from_mount.go
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/exporters_bus.go
  pkg/exporters/stdout_exporter.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
  pkg/scan/clamav/clamav.go
  pkg/scan/clamav/config.go
  pkg/scan/fileutil.go
  pkg/scan/k8sutil.go
  pkg/scan/overlay.go
  pkg/scan/types.go
Labels: enhancement

#141 Bumping kapprofiler to v0.0.43
  go.mod
  go.sum
Labels: enhancement

#143 Bugfix/profile missing
  chart/kubecop/files/freshclam.conf
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/approfilecache/cache_test.go
  pkg/approfilecache/types.go
  pkg/engine/engine_test.go
  pkg/engine/rule/mock.go
  pkg/engine/rule/r0004_unexpected_capability_used.go
  pkg/exporters/README.md
Labels: requires-system-test, Bug fix

#146 Bumped kapprofiler to newer version
  go.mod
  go.sum
Labels: enhancement, requires-system-test

#147 Bumping kapprofiler with field selector
  go.mod
  go.sum
Labels: enhancement

#151 Fixing some typos in the demo and bumping ig version
  demo/README.md
  demo/general_attack/webapp/setup.sh
  go.mod
  go.sum
Labels: requires-system-test, Bug fix
