Repository armosec/kubecop, pull requests merged in 2024-03, with the labels that each got.

#186 add-http-exporter + UTs
  README.md
  chart/kubecop/Chart.yaml
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
  pkg/exporters/README.md
  pkg/exporters/exporters_bus.go
  pkg/exporters/http_exporter.go
  pkg/exporters/http_exporter_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#187 Add tolerations to controller-statefulset and deamonset
  chart/kubecop/templates/controller-statefulset.yaml
  chart/kubecop/templates/deamonset.yaml
  chart/kubecop/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#191 Removing ssh rule from system tests
  system-tests/all_alerts_from_malicious_app.py
Labels: requires-system-test, bug_fix, Review effort [1-5]: 1
