Repository armosec/kubecop, pull requests merged in 2024-02, with the labels that each got.

#166 Limiting KubeCop RBAC
  chart/kubecop/templates/clusterrole.yaml
  chart/kubecop/templates/clusterrolebinding.yaml
  chart/kubecop/templates/controller-statefulset.yaml
  chart/kubecop/values.yaml
Labels: enhancement, requires-system-test, Review effort [1-5]: 2

#165 Feature/namespaced profiles
  .github/workflows/namespaced-system-tests.yaml
  cmd/main.go
  go.mod
  go.sum
  pkg/approfilecache/cache.go
  pkg/approfilecache/cache_test.go
  system-tests/all_alerts_from_malicious_app.py
  system-tests/basic_alert_tests.py
  system-tests/basic_load_activities.py
  system-tests/creation_app_profile_memory_leak.py
  system-tests/finalization_alert_test.py
  system-tests/kubernetes_wrappers.py
  system-tests/load_10k_alerts_no_memory.py
  system-tests/resources/malicious-job-app-profile-namespaced.yaml
  system-tests/resources/nginx-app-profile-namespaced.yaml
Labels: enhancement, requires-system-test, Review effort [1-5]: 3, requires-namespaced-system-test

#168 Fixing watche
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#169 Bumped kapprofiler
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#171 Bugfix/watcher cache
  go.mod
  go.sum
  pkg/approfilecache/cache.go
Labels: enhancement, requires-system-test, bug_fix, Review effort [1-5]: 2

#170 Adding namespaced docs
  README.md
Labels: documentation, Review effort [1-5]: 1

#172 Adding services permissions
  chart/kubecop/templates/clusterrole.yaml
Labels: bug_fix, Review effort [1-5]: 1

#174 Update Helm chart version and tag to v0.0.32
  .github/workflows/release-helm-chart.yaml
  chart/kubecop/Chart.yaml
  chart/kubecop/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#175 Adding with param to workflow
  .github/workflows/release-helm-chart.yaml
Labels: enhancement

#176 Feature/helm release
  .github/workflows/release-helm-chart.yaml
Labels: enhancement, Review effort [1-5]: 1

#177 Adding randomx crypto miner support and fix watcher by bumping kappro…
  chart/kubecop/Chart.yaml
  chart/kubecop/values.yaml
  cmd/main.go
  go.mod
  go.sum
  pkg/engine/router.go
  pkg/engine/rule/r1007_crypto_miners.go
  pkg/engine/rule/r1007_crypto_miners_test.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#181 Add cacheLock for thread safety
  pkg/approfilecache/cache.go
Labels: enhancement, requires-system-test, Review effort [1-5]: 2

#182 v35
  chart/kubecop/Chart.yaml
  chart/kubecop/values.yaml
Labels: enhancement, Review effort [1-5]: 2

#183 Feature/randomx detection
  demo/miner/Containerfile
  demo/miner/Dockerfile
  demo/miner/miner-pod.yaml
  demo/miner/xmr-k8s-miner.py
  go.mod
  go.sum
  pkg/engine/rule/r1007_crypto_miners.go
  pkg/engine/stats_prometheus.go
Labels: documentation, enhancement, requires-system-test, Review effort [1-5]: 2
